//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3082.
// 
#pragma warning disable 1591

namespace WebPortal.Itm {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WptServiceSoap", Namespace="http://tempuri.org/")]
    public partial class WptService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMemberOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetApprvLoanOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCollwhoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDeptOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDeptStmOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDivAvgOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetKeepingOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLoanOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLoanStmOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRegMemOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertRegOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRegUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateRegUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetShareOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetShareStmOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetWhocollOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckMemberOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserPasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback ChangePasswordOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WptService() {
            this.Url = global::WebPortal.Properties.Settings.Default.WebPortal_Itm_WptService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event GetMemberCompletedEventHandler GetMemberCompleted;
        
        /// <remarks/>
        public event GetApprvLoanCompletedEventHandler GetApprvLoanCompleted;
        
        /// <remarks/>
        public event GetCollwhoCompletedEventHandler GetCollwhoCompleted;
        
        /// <remarks/>
        public event GetDeptCompletedEventHandler GetDeptCompleted;
        
        /// <remarks/>
        public event GetDeptStmCompletedEventHandler GetDeptStmCompleted;
        
        /// <remarks/>
        public event GetDivAvgCompletedEventHandler GetDivAvgCompleted;
        
        /// <remarks/>
        public event GetKeepingCompletedEventHandler GetKeepingCompleted;
        
        /// <remarks/>
        public event GetLoanCompletedEventHandler GetLoanCompleted;
        
        /// <remarks/>
        public event GetLoanStmCompletedEventHandler GetLoanStmCompleted;
        
        /// <remarks/>
        public event GetRegMemCompletedEventHandler GetRegMemCompleted;
        
        /// <remarks/>
        public event InsertRegCompletedEventHandler InsertRegCompleted;
        
        /// <remarks/>
        public event GetRegUserCompletedEventHandler GetRegUserCompleted;
        
        /// <remarks/>
        public event UpdateRegUserCompletedEventHandler UpdateRegUserCompleted;
        
        /// <remarks/>
        public event GetShareCompletedEventHandler GetShareCompleted;
        
        /// <remarks/>
        public event GetShareStmCompletedEventHandler GetShareStmCompleted;
        
        /// <remarks/>
        public event GetWhocollCompletedEventHandler GetWhocollCompleted;
        
        /// <remarks/>
        public event CheckMemberCompletedEventHandler CheckMemberCompleted;
        
        /// <remarks/>
        public event GetLoginCompletedEventHandler GetLoginCompleted;
        
        /// <remarks/>
        public event GetUserPasswordCompletedEventHandler GetUserPasswordCompleted;
        
        /// <remarks/>
        public event ChangePasswordCompletedEventHandler ChangePasswordCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMember", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CWmember[] GetMember(string memberNo) {
            object[] results = this.Invoke("GetMember", new object[] {
                        memberNo});
            return ((CWmember[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMemberAsync(string memberNo) {
            this.GetMemberAsync(memberNo, null);
        }
        
        /// <remarks/>
        public void GetMemberAsync(string memberNo, object userState) {
            if ((this.GetMemberOperationCompleted == null)) {
                this.GetMemberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMemberOperationCompleted);
            }
            this.InvokeAsync("GetMember", new object[] {
                        memberNo}, this.GetMemberOperationCompleted, userState);
        }
        
        private void OnGetMemberOperationCompleted(object arg) {
            if ((this.GetMemberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMemberCompleted(this, new GetMemberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetApprvLoan", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CWApprvLoan[] GetApprvLoan(string memberNo) {
            object[] results = this.Invoke("GetApprvLoan", new object[] {
                        memberNo});
            return ((CWApprvLoan[])(results[0]));
        }
        
        /// <remarks/>
        public void GetApprvLoanAsync(string memberNo) {
            this.GetApprvLoanAsync(memberNo, null);
        }
        
        /// <remarks/>
        public void GetApprvLoanAsync(string memberNo, object userState) {
            if ((this.GetApprvLoanOperationCompleted == null)) {
                this.GetApprvLoanOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetApprvLoanOperationCompleted);
            }
            this.InvokeAsync("GetApprvLoan", new object[] {
                        memberNo}, this.GetApprvLoanOperationCompleted, userState);
        }
        
        private void OnGetApprvLoanOperationCompleted(object arg) {
            if ((this.GetApprvLoanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetApprvLoanCompleted(this, new GetApprvLoanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCollwho", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CWCollWho[] GetCollwho(string memberNO) {
            object[] results = this.Invoke("GetCollwho", new object[] {
                        memberNO});
            return ((CWCollWho[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCollwhoAsync(string memberNO) {
            this.GetCollwhoAsync(memberNO, null);
        }
        
        /// <remarks/>
        public void GetCollwhoAsync(string memberNO, object userState) {
            if ((this.GetCollwhoOperationCompleted == null)) {
                this.GetCollwhoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCollwhoOperationCompleted);
            }
            this.InvokeAsync("GetCollwho", new object[] {
                        memberNO}, this.GetCollwhoOperationCompleted, userState);
        }
        
        private void OnGetCollwhoOperationCompleted(object arg) {
            if ((this.GetCollwhoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCollwhoCompleted(this, new GetCollwhoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDept", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CWDept[] GetDept(string memberNo) {
            object[] results = this.Invoke("GetDept", new object[] {
                        memberNo});
            return ((CWDept[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDeptAsync(string memberNo) {
            this.GetDeptAsync(memberNo, null);
        }
        
        /// <remarks/>
        public void GetDeptAsync(string memberNo, object userState) {
            if ((this.GetDeptOperationCompleted == null)) {
                this.GetDeptOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDeptOperationCompleted);
            }
            this.InvokeAsync("GetDept", new object[] {
                        memberNo}, this.GetDeptOperationCompleted, userState);
        }
        
        private void OnGetDeptOperationCompleted(object arg) {
            if ((this.GetDeptCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDeptCompleted(this, new GetDeptCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDeptStm", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CWDeptStm[] GetDeptStm(string deptAccNo) {
            object[] results = this.Invoke("GetDeptStm", new object[] {
                        deptAccNo});
            return ((CWDeptStm[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDeptStmAsync(string deptAccNo) {
            this.GetDeptStmAsync(deptAccNo, null);
        }
        
        /// <remarks/>
        public void GetDeptStmAsync(string deptAccNo, object userState) {
            if ((this.GetDeptStmOperationCompleted == null)) {
                this.GetDeptStmOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDeptStmOperationCompleted);
            }
            this.InvokeAsync("GetDeptStm", new object[] {
                        deptAccNo}, this.GetDeptStmOperationCompleted, userState);
        }
        
        private void OnGetDeptStmOperationCompleted(object arg) {
            if ((this.GetDeptStmCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDeptStmCompleted(this, new GetDeptStmCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDivAvg", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CWDivAvg[] GetDivAvg(string memberNo) {
            object[] results = this.Invoke("GetDivAvg", new object[] {
                        memberNo});
            return ((CWDivAvg[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDivAvgAsync(string memberNo) {
            this.GetDivAvgAsync(memberNo, null);
        }
        
        /// <remarks/>
        public void GetDivAvgAsync(string memberNo, object userState) {
            if ((this.GetDivAvgOperationCompleted == null)) {
                this.GetDivAvgOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDivAvgOperationCompleted);
            }
            this.InvokeAsync("GetDivAvg", new object[] {
                        memberNo}, this.GetDivAvgOperationCompleted, userState);
        }
        
        private void OnGetDivAvgOperationCompleted(object arg) {
            if ((this.GetDivAvgCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDivAvgCompleted(this, new GetDivAvgCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetKeeping", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CWKeeping[] GetKeeping(string memberNo) {
            object[] results = this.Invoke("GetKeeping", new object[] {
                        memberNo});
            return ((CWKeeping[])(results[0]));
        }
        
        /// <remarks/>
        public void GetKeepingAsync(string memberNo) {
            this.GetKeepingAsync(memberNo, null);
        }
        
        /// <remarks/>
        public void GetKeepingAsync(string memberNo, object userState) {
            if ((this.GetKeepingOperationCompleted == null)) {
                this.GetKeepingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetKeepingOperationCompleted);
            }
            this.InvokeAsync("GetKeeping", new object[] {
                        memberNo}, this.GetKeepingOperationCompleted, userState);
        }
        
        private void OnGetKeepingOperationCompleted(object arg) {
            if ((this.GetKeepingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetKeepingCompleted(this, new GetKeepingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLoan", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CWLoan[] GetLoan(string memberNo) {
            object[] results = this.Invoke("GetLoan", new object[] {
                        memberNo});
            return ((CWLoan[])(results[0]));
        }
        
        /// <remarks/>
        public void GetLoanAsync(string memberNo) {
            this.GetLoanAsync(memberNo, null);
        }
        
        /// <remarks/>
        public void GetLoanAsync(string memberNo, object userState) {
            if ((this.GetLoanOperationCompleted == null)) {
                this.GetLoanOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLoanOperationCompleted);
            }
            this.InvokeAsync("GetLoan", new object[] {
                        memberNo}, this.GetLoanOperationCompleted, userState);
        }
        
        private void OnGetLoanOperationCompleted(object arg) {
            if ((this.GetLoanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLoanCompleted(this, new GetLoanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLoanStm", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CWLoanStm[] GetLoanStm(string lnContNo) {
            object[] results = this.Invoke("GetLoanStm", new object[] {
                        lnContNo});
            return ((CWLoanStm[])(results[0]));
        }
        
        /// <remarks/>
        public void GetLoanStmAsync(string lnContNo) {
            this.GetLoanStmAsync(lnContNo, null);
        }
        
        /// <remarks/>
        public void GetLoanStmAsync(string lnContNo, object userState) {
            if ((this.GetLoanStmOperationCompleted == null)) {
                this.GetLoanStmOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLoanStmOperationCompleted);
            }
            this.InvokeAsync("GetLoanStm", new object[] {
                        lnContNo}, this.GetLoanStmOperationCompleted, userState);
        }
        
        private void OnGetLoanStmOperationCompleted(object arg) {
            if ((this.GetLoanStmCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLoanStmCompleted(this, new GetLoanStmCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRegMem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CWRegister[] GetRegMem(string memberNO) {
            object[] results = this.Invoke("GetRegMem", new object[] {
                        memberNO});
            return ((CWRegister[])(results[0]));
        }
        
        /// <remarks/>
        public void GetRegMemAsync(string memberNO) {
            this.GetRegMemAsync(memberNO, null);
        }
        
        /// <remarks/>
        public void GetRegMemAsync(string memberNO, object userState) {
            if ((this.GetRegMemOperationCompleted == null)) {
                this.GetRegMemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRegMemOperationCompleted);
            }
            this.InvokeAsync("GetRegMem", new object[] {
                        memberNO}, this.GetRegMemOperationCompleted, userState);
        }
        
        private void OnGetRegMemOperationCompleted(object arg) {
            if ((this.GetRegMemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRegMemCompleted(this, new GetRegMemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertReg", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int InsertReg(string member, string name, string surname, string cardId, string email, string usn, string pwd) {
            object[] results = this.Invoke("InsertReg", new object[] {
                        member,
                        name,
                        surname,
                        cardId,
                        email,
                        usn,
                        pwd});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void InsertRegAsync(string member, string name, string surname, string cardId, string email, string usn, string pwd) {
            this.InsertRegAsync(member, name, surname, cardId, email, usn, pwd, null);
        }
        
        /// <remarks/>
        public void InsertRegAsync(string member, string name, string surname, string cardId, string email, string usn, string pwd, object userState) {
            if ((this.InsertRegOperationCompleted == null)) {
                this.InsertRegOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertRegOperationCompleted);
            }
            this.InvokeAsync("InsertReg", new object[] {
                        member,
                        name,
                        surname,
                        cardId,
                        email,
                        usn,
                        pwd}, this.InsertRegOperationCompleted, userState);
        }
        
        private void OnInsertRegOperationCompleted(object arg) {
            if ((this.InsertRegCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertRegCompleted(this, new InsertRegCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRegUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CWRegister[] GetRegUser(string memberNo) {
            object[] results = this.Invoke("GetRegUser", new object[] {
                        memberNo});
            return ((CWRegister[])(results[0]));
        }
        
        /// <remarks/>
        public void GetRegUserAsync(string memberNo) {
            this.GetRegUserAsync(memberNo, null);
        }
        
        /// <remarks/>
        public void GetRegUserAsync(string memberNo, object userState) {
            if ((this.GetRegUserOperationCompleted == null)) {
                this.GetRegUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRegUserOperationCompleted);
            }
            this.InvokeAsync("GetRegUser", new object[] {
                        memberNo}, this.GetRegUserOperationCompleted, userState);
        }
        
        private void OnGetRegUserOperationCompleted(object arg) {
            if ((this.GetRegUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRegUserCompleted(this, new GetRegUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateRegUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UpdateRegUser(string member, string usn, string pwd) {
            object[] results = this.Invoke("UpdateRegUser", new object[] {
                        member,
                        usn,
                        pwd});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateRegUserAsync(string member, string usn, string pwd) {
            this.UpdateRegUserAsync(member, usn, pwd, null);
        }
        
        /// <remarks/>
        public void UpdateRegUserAsync(string member, string usn, string pwd, object userState) {
            if ((this.UpdateRegUserOperationCompleted == null)) {
                this.UpdateRegUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateRegUserOperationCompleted);
            }
            this.InvokeAsync("UpdateRegUser", new object[] {
                        member,
                        usn,
                        pwd}, this.UpdateRegUserOperationCompleted, userState);
        }
        
        private void OnUpdateRegUserOperationCompleted(object arg) {
            if ((this.UpdateRegUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateRegUserCompleted(this, new UpdateRegUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetShare", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CWShare[] GetShare(string memberNo) {
            object[] results = this.Invoke("GetShare", new object[] {
                        memberNo});
            return ((CWShare[])(results[0]));
        }
        
        /// <remarks/>
        public void GetShareAsync(string memberNo) {
            this.GetShareAsync(memberNo, null);
        }
        
        /// <remarks/>
        public void GetShareAsync(string memberNo, object userState) {
            if ((this.GetShareOperationCompleted == null)) {
                this.GetShareOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetShareOperationCompleted);
            }
            this.InvokeAsync("GetShare", new object[] {
                        memberNo}, this.GetShareOperationCompleted, userState);
        }
        
        private void OnGetShareOperationCompleted(object arg) {
            if ((this.GetShareCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetShareCompleted(this, new GetShareCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetShareStm", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CWShareStm[] GetShareStm(string memberNo) {
            object[] results = this.Invoke("GetShareStm", new object[] {
                        memberNo});
            return ((CWShareStm[])(results[0]));
        }
        
        /// <remarks/>
        public void GetShareStmAsync(string memberNo) {
            this.GetShareStmAsync(memberNo, null);
        }
        
        /// <remarks/>
        public void GetShareStmAsync(string memberNo, object userState) {
            if ((this.GetShareStmOperationCompleted == null)) {
                this.GetShareStmOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetShareStmOperationCompleted);
            }
            this.InvokeAsync("GetShareStm", new object[] {
                        memberNo}, this.GetShareStmOperationCompleted, userState);
        }
        
        private void OnGetShareStmOperationCompleted(object arg) {
            if ((this.GetShareStmCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetShareStmCompleted(this, new GetShareStmCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetWhocoll", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CWWhocoll[] GetWhocoll(string memberNo) {
            object[] results = this.Invoke("GetWhocoll", new object[] {
                        memberNo});
            return ((CWWhocoll[])(results[0]));
        }
        
        /// <remarks/>
        public void GetWhocollAsync(string memberNo) {
            this.GetWhocollAsync(memberNo, null);
        }
        
        /// <remarks/>
        public void GetWhocollAsync(string memberNo, object userState) {
            if ((this.GetWhocollOperationCompleted == null)) {
                this.GetWhocollOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWhocollOperationCompleted);
            }
            this.InvokeAsync("GetWhocoll", new object[] {
                        memberNo}, this.GetWhocollOperationCompleted, userState);
        }
        
        private void OnGetWhocollOperationCompleted(object arg) {
            if ((this.GetWhocollCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWhocollCompleted(this, new GetWhocollCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckMember", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CheckMember(string memberNo, string cardPerson) {
            object[] results = this.Invoke("CheckMember", new object[] {
                        memberNo,
                        cardPerson});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CheckMemberAsync(string memberNo, string cardPerson) {
            this.CheckMemberAsync(memberNo, cardPerson, null);
        }
        
        /// <remarks/>
        public void CheckMemberAsync(string memberNo, string cardPerson, object userState) {
            if ((this.CheckMemberOperationCompleted == null)) {
                this.CheckMemberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckMemberOperationCompleted);
            }
            this.InvokeAsync("CheckMember", new object[] {
                        memberNo,
                        cardPerson}, this.CheckMemberOperationCompleted, userState);
        }
        
        private void OnCheckMemberOperationCompleted(object arg) {
            if ((this.CheckMemberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckMemberCompleted(this, new CheckMemberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLogin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetLogin(string[] arr) {
            object[] results = this.Invoke("GetLogin", new object[] {
                        arr});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetLoginAsync(string[] arr) {
            this.GetLoginAsync(arr, null);
        }
        
        /// <remarks/>
        public void GetLoginAsync(string[] arr, object userState) {
            if ((this.GetLoginOperationCompleted == null)) {
                this.GetLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLoginOperationCompleted);
            }
            this.InvokeAsync("GetLogin", new object[] {
                        arr}, this.GetLoginOperationCompleted, userState);
        }
        
        private void OnGetLoginOperationCompleted(object arg) {
            if ((this.GetLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLoginCompleted(this, new GetLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserPassword", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetUserPassword(string memberNo, string emailAddr) {
            object[] results = this.Invoke("GetUserPassword", new object[] {
                        memberNo,
                        emailAddr});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserPasswordAsync(string memberNo, string emailAddr) {
            this.GetUserPasswordAsync(memberNo, emailAddr, null);
        }
        
        /// <remarks/>
        public void GetUserPasswordAsync(string memberNo, string emailAddr, object userState) {
            if ((this.GetUserPasswordOperationCompleted == null)) {
                this.GetUserPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserPasswordOperationCompleted);
            }
            this.InvokeAsync("GetUserPassword", new object[] {
                        memberNo,
                        emailAddr}, this.GetUserPasswordOperationCompleted, userState);
        }
        
        private void OnGetUserPasswordOperationCompleted(object arg) {
            if ((this.GetUserPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserPasswordCompleted(this, new GetUserPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ChangePassword", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ChangePassword(string memberNO, string user, string oldpwd, string newpwd, string confpwd) {
            object[] results = this.Invoke("ChangePassword", new object[] {
                        memberNO,
                        user,
                        oldpwd,
                        newpwd,
                        confpwd});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ChangePasswordAsync(string memberNO, string user, string oldpwd, string newpwd, string confpwd) {
            this.ChangePasswordAsync(memberNO, user, oldpwd, newpwd, confpwd, null);
        }
        
        /// <remarks/>
        public void ChangePasswordAsync(string memberNO, string user, string oldpwd, string newpwd, string confpwd, object userState) {
            if ((this.ChangePasswordOperationCompleted == null)) {
                this.ChangePasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChangePasswordOperationCompleted);
            }
            this.InvokeAsync("ChangePassword", new object[] {
                        memberNO,
                        user,
                        oldpwd,
                        newpwd,
                        confpwd}, this.ChangePasswordOperationCompleted, userState);
        }
        
        private void OnChangePasswordOperationCompleted(object arg) {
            if ((this.ChangePasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChangePasswordCompleted(this, new ChangePasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CWmember {
        
        private string membNameField;
        
        private string membSurnameField;
        
        private string memberNoField;
        
        private System.DateTime memberDateField;
        
        private System.DateTime birthDateField;
        
        /// <remarks/>
        public string MembName {
            get {
                return this.membNameField;
            }
            set {
                this.membNameField = value;
            }
        }
        
        /// <remarks/>
        public string MembSurname {
            get {
                return this.membSurnameField;
            }
            set {
                this.membSurnameField = value;
            }
        }
        
        /// <remarks/>
        public string MemberNo {
            get {
                return this.memberNoField;
            }
            set {
                this.memberNoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime MemberDate {
            get {
                return this.memberDateField;
            }
            set {
                this.memberDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime BirthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CWWhocoll {
        
        private string lnContNoField;
        
        private string descriptionField;
        
        private double prncBalField;
        
        /// <remarks/>
        public string LnContNo {
            get {
                return this.lnContNoField;
            }
            set {
                this.lnContNoField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public double PrncBal {
            get {
                return this.prncBalField;
            }
            set {
                this.prncBalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CWShareStm {
        
        private string shareTypeCodeField;
        
        private string shaItemTypeCodeField;
        
        private string shaItemTypeDescField;
        
        private double shareAmountField;
        
        private double shareValueField;
        
        private int seqNoField;
        
        private System.DateTime oprDateField;
        
        /// <remarks/>
        public string ShareTypeCode {
            get {
                return this.shareTypeCodeField;
            }
            set {
                this.shareTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ShaItemTypeCode {
            get {
                return this.shaItemTypeCodeField;
            }
            set {
                this.shaItemTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ShaItemTypeDesc {
            get {
                return this.shaItemTypeDescField;
            }
            set {
                this.shaItemTypeDescField = value;
            }
        }
        
        /// <remarks/>
        public double ShareAmount {
            get {
                return this.shareAmountField;
            }
            set {
                this.shareAmountField = value;
            }
        }
        
        /// <remarks/>
        public double ShareValue {
            get {
                return this.shareValueField;
            }
            set {
                this.shareValueField = value;
            }
        }
        
        /// <remarks/>
        public int SeqNo {
            get {
                return this.seqNoField;
            }
            set {
                this.seqNoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime OprDate {
            get {
                return this.oprDateField;
            }
            set {
                this.oprDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CWShare {
        
        private double shareStkAmtField;
        
        private double shareBeginAmtField;
        
        private double periodShareAmtField;
        
        private double shareValueField;
        
        private double periodBaseAmatField;
        
        private int lastPeriodField;
        
        /// <remarks/>
        public double ShareStkAmt {
            get {
                return this.shareStkAmtField;
            }
            set {
                this.shareStkAmtField = value;
            }
        }
        
        /// <remarks/>
        public double ShareBeginAmt {
            get {
                return this.shareBeginAmtField;
            }
            set {
                this.shareBeginAmtField = value;
            }
        }
        
        /// <remarks/>
        public double PeriodShareAmt {
            get {
                return this.periodShareAmtField;
            }
            set {
                this.periodShareAmtField = value;
            }
        }
        
        /// <remarks/>
        public double ShareValue {
            get {
                return this.shareValueField;
            }
            set {
                this.shareValueField = value;
            }
        }
        
        /// <remarks/>
        public double PeriodBaseAmat {
            get {
                return this.periodBaseAmatField;
            }
            set {
                this.periodBaseAmatField = value;
            }
        }
        
        /// <remarks/>
        public int LastPeriod {
            get {
                return this.lastPeriodField;
            }
            set {
                this.lastPeriodField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CWRegister {
        
        private string memberNoField;
        
        private string membNameField;
        
        private string membSurnameField;
        
        private string cardPersonField;
        
        private string userNameField;
        
        private string passwordField;
        
        private string emailAddressField;
        
        private string confPassField;
        
        private string oldPassField;
        
        private string newPassField;
        
        /// <remarks/>
        public string MemberNo {
            get {
                return this.memberNoField;
            }
            set {
                this.memberNoField = value;
            }
        }
        
        /// <remarks/>
        public string MembName {
            get {
                return this.membNameField;
            }
            set {
                this.membNameField = value;
            }
        }
        
        /// <remarks/>
        public string MembSurname {
            get {
                return this.membSurnameField;
            }
            set {
                this.membSurnameField = value;
            }
        }
        
        /// <remarks/>
        public string CardPerson {
            get {
                return this.cardPersonField;
            }
            set {
                this.cardPersonField = value;
            }
        }
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ConfPass {
            get {
                return this.confPassField;
            }
            set {
                this.confPassField = value;
            }
        }
        
        /// <remarks/>
        public string OldPass {
            get {
                return this.oldPassField;
            }
            set {
                this.oldPassField = value;
            }
        }
        
        /// <remarks/>
        public string NewPass {
            get {
                return this.newPassField;
            }
            set {
                this.newPassField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CWLoanStm {
        
        private string lncontNoField;
        
        private string branchIdField;
        
        private string lnTypeCodeField;
        
        private string refDocNoField;
        
        private string moneyTypeCodeField;
        
        private string entryIdField;
        
        private int seqNOField;
        
        private int periodField;
        
        private int itemStatusField;
        
        private System.DateTime slipDateField;
        
        private System.DateTime oprDateField;
        
        private System.DateTime calintFormField;
        
        private System.DateTime calintToField;
        
        private System.DateTime entryDateField;
        
        private double prncPaymentField;
        
        private double interestPaymentField;
        
        private double prncBalField;
        
        private double bfintarrearAmtField;
        
        private double interestPeriodField;
        
        private double interestArrearField;
        
        private double interestReturnField;
        
        /// <remarks/>
        public string LncontNo {
            get {
                return this.lncontNoField;
            }
            set {
                this.lncontNoField = value;
            }
        }
        
        /// <remarks/>
        public string BranchId {
            get {
                return this.branchIdField;
            }
            set {
                this.branchIdField = value;
            }
        }
        
        /// <remarks/>
        public string LnTypeCode {
            get {
                return this.lnTypeCodeField;
            }
            set {
                this.lnTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        public string RefDocNo {
            get {
                return this.refDocNoField;
            }
            set {
                this.refDocNoField = value;
            }
        }
        
        /// <remarks/>
        public string MoneyTypeCode {
            get {
                return this.moneyTypeCodeField;
            }
            set {
                this.moneyTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        public string EntryId {
            get {
                return this.entryIdField;
            }
            set {
                this.entryIdField = value;
            }
        }
        
        /// <remarks/>
        public int SeqNO {
            get {
                return this.seqNOField;
            }
            set {
                this.seqNOField = value;
            }
        }
        
        /// <remarks/>
        public int Period {
            get {
                return this.periodField;
            }
            set {
                this.periodField = value;
            }
        }
        
        /// <remarks/>
        public int ItemStatus {
            get {
                return this.itemStatusField;
            }
            set {
                this.itemStatusField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SlipDate {
            get {
                return this.slipDateField;
            }
            set {
                this.slipDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime OprDate {
            get {
                return this.oprDateField;
            }
            set {
                this.oprDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CalintForm {
            get {
                return this.calintFormField;
            }
            set {
                this.calintFormField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CalintTo {
            get {
                return this.calintToField;
            }
            set {
                this.calintToField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EntryDate {
            get {
                return this.entryDateField;
            }
            set {
                this.entryDateField = value;
            }
        }
        
        /// <remarks/>
        public double PrncPayment {
            get {
                return this.prncPaymentField;
            }
            set {
                this.prncPaymentField = value;
            }
        }
        
        /// <remarks/>
        public double InterestPayment {
            get {
                return this.interestPaymentField;
            }
            set {
                this.interestPaymentField = value;
            }
        }
        
        /// <remarks/>
        public double PrncBal {
            get {
                return this.prncBalField;
            }
            set {
                this.prncBalField = value;
            }
        }
        
        /// <remarks/>
        public double BfintarrearAmt {
            get {
                return this.bfintarrearAmtField;
            }
            set {
                this.bfintarrearAmtField = value;
            }
        }
        
        /// <remarks/>
        public double InterestPeriod {
            get {
                return this.interestPeriodField;
            }
            set {
                this.interestPeriodField = value;
            }
        }
        
        /// <remarks/>
        public double InterestArrear {
            get {
                return this.interestArrearField;
            }
            set {
                this.interestArrearField = value;
            }
        }
        
        /// <remarks/>
        public double InterestReturn {
            get {
                return this.interestReturnField;
            }
            set {
                this.interestReturnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CWLoan {
        
        private string lnContNoField;
        
        private string lnTypeCodeField;
        
        private double prncBalField;
        
        private double periodPaymentField;
        
        private double lnReqAmtField;
        
        private System.DateTime startContDateField;
        
        /// <remarks/>
        public string LnContNo {
            get {
                return this.lnContNoField;
            }
            set {
                this.lnContNoField = value;
            }
        }
        
        /// <remarks/>
        public string LnTypeCode {
            get {
                return this.lnTypeCodeField;
            }
            set {
                this.lnTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        public double PrncBal {
            get {
                return this.prncBalField;
            }
            set {
                this.prncBalField = value;
            }
        }
        
        /// <remarks/>
        public double PeriodPayment {
            get {
                return this.periodPaymentField;
            }
            set {
                this.periodPaymentField = value;
            }
        }
        
        /// <remarks/>
        public double LnReqAmt {
            get {
                return this.lnReqAmtField;
            }
            set {
                this.lnReqAmtField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime StartContDate {
            get {
                return this.startContDateField;
            }
            set {
                this.startContDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CWKeeping {
        
        private int seqnoField;
        
        private string keepTypeDescField;
        
        private string recvPeriodField;
        
        private double itemPaymentField;
        
        /// <remarks/>
        public int Seqno {
            get {
                return this.seqnoField;
            }
            set {
                this.seqnoField = value;
            }
        }
        
        /// <remarks/>
        public string KeepTypeDesc {
            get {
                return this.keepTypeDescField;
            }
            set {
                this.keepTypeDescField = value;
            }
        }
        
        /// <remarks/>
        public string RecvPeriod {
            get {
                return this.recvPeriodField;
            }
            set {
                this.recvPeriodField = value;
            }
        }
        
        /// <remarks/>
        public double ItemPayment {
            get {
                return this.itemPaymentField;
            }
            set {
                this.itemPaymentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CWDivAvg {
        
        private int divAvgYearField;
        
        private double divAmtField;
        
        private double avgAmtField;
        
        /// <remarks/>
        public int DivAvgYear {
            get {
                return this.divAvgYearField;
            }
            set {
                this.divAvgYearField = value;
            }
        }
        
        /// <remarks/>
        public double DivAmt {
            get {
                return this.divAmtField;
            }
            set {
                this.divAmtField = value;
            }
        }
        
        /// <remarks/>
        public double AvgAmt {
            get {
                return this.avgAmtField;
            }
            set {
                this.avgAmtField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CWDeptStm {
        
        private double deptItemAmtField;
        
        private double prncBalField;
        
        private int seqNoField;
        
        private string deptTypeCodeField;
        
        private string deptAccNoField;
        
        private System.DateTime oprDateField;
        
        /// <remarks/>
        public double DeptItemAmt {
            get {
                return this.deptItemAmtField;
            }
            set {
                this.deptItemAmtField = value;
            }
        }
        
        /// <remarks/>
        public double PrncBal {
            get {
                return this.prncBalField;
            }
            set {
                this.prncBalField = value;
            }
        }
        
        /// <remarks/>
        public int SeqNo {
            get {
                return this.seqNoField;
            }
            set {
                this.seqNoField = value;
            }
        }
        
        /// <remarks/>
        public string DeptTypeCode {
            get {
                return this.deptTypeCodeField;
            }
            set {
                this.deptTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        public string DeptAccNo {
            get {
                return this.deptAccNoField;
            }
            set {
                this.deptAccNoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime OprDate {
            get {
                return this.oprDateField;
            }
            set {
                this.oprDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CWDept {
        
        private string deptAccNoField;
        
        private string deptAccNameField;
        
        private string deptTypeDescField;
        
        private double prncbalField;
        
        /// <remarks/>
        public string DeptAccNo {
            get {
                return this.deptAccNoField;
            }
            set {
                this.deptAccNoField = value;
            }
        }
        
        /// <remarks/>
        public string DeptAccName {
            get {
                return this.deptAccNameField;
            }
            set {
                this.deptAccNameField = value;
            }
        }
        
        /// <remarks/>
        public string DeptTypeDesc {
            get {
                return this.deptTypeDescField;
            }
            set {
                this.deptTypeDescField = value;
            }
        }
        
        /// <remarks/>
        public double Prncbal {
            get {
                return this.prncbalField;
            }
            set {
                this.prncbalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CWCollWho {
        
        private string lnContNoField;
        
        private string descriptionField;
        
        private string membNameField;
        
        private string membSurnameField;
        
        private double _PrincBalField;
        
        /// <remarks/>
        public string LnContNo {
            get {
                return this.lnContNoField;
            }
            set {
                this.lnContNoField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string MembName {
            get {
                return this.membNameField;
            }
            set {
                this.membNameField = value;
            }
        }
        
        /// <remarks/>
        public string MembSurname {
            get {
                return this.membSurnameField;
            }
            set {
                this.membSurnameField = value;
            }
        }
        
        /// <remarks/>
        public double _PrincBal {
            get {
                return this._PrincBalField;
            }
            set {
                this._PrincBalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CWApprvLoan {
        
        private string lnReqDocNoField;
        
        private string lnTypeCodeField;
        
        private string lnTypeDescField;
        
        private string lnContNOField;
        
        private double lnReqAmtField;
        
        private double lnAppvAmtField;
        
        private int lnReqStatusField;
        
        private System.DateTime appvDateField;
        
        /// <remarks/>
        public string LnReqDocNo {
            get {
                return this.lnReqDocNoField;
            }
            set {
                this.lnReqDocNoField = value;
            }
        }
        
        /// <remarks/>
        public string LnTypeCode {
            get {
                return this.lnTypeCodeField;
            }
            set {
                this.lnTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        public string LnTypeDesc {
            get {
                return this.lnTypeDescField;
            }
            set {
                this.lnTypeDescField = value;
            }
        }
        
        /// <remarks/>
        public string LnContNO {
            get {
                return this.lnContNOField;
            }
            set {
                this.lnContNOField = value;
            }
        }
        
        /// <remarks/>
        public double LnReqAmt {
            get {
                return this.lnReqAmtField;
            }
            set {
                this.lnReqAmtField = value;
            }
        }
        
        /// <remarks/>
        public double LnAppvAmt {
            get {
                return this.lnAppvAmtField;
            }
            set {
                this.lnAppvAmtField = value;
            }
        }
        
        /// <remarks/>
        public int LnReqStatus {
            get {
                return this.lnReqStatusField;
            }
            set {
                this.lnReqStatusField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime AppvDate {
            get {
                return this.appvDateField;
            }
            set {
                this.appvDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetMemberCompletedEventHandler(object sender, GetMemberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMemberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMemberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CWmember[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CWmember[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetApprvLoanCompletedEventHandler(object sender, GetApprvLoanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetApprvLoanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetApprvLoanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CWApprvLoan[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CWApprvLoan[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetCollwhoCompletedEventHandler(object sender, GetCollwhoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCollwhoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCollwhoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CWCollWho[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CWCollWho[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetDeptCompletedEventHandler(object sender, GetDeptCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDeptCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDeptCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CWDept[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CWDept[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetDeptStmCompletedEventHandler(object sender, GetDeptStmCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDeptStmCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDeptStmCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CWDeptStm[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CWDeptStm[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetDivAvgCompletedEventHandler(object sender, GetDivAvgCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDivAvgCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDivAvgCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CWDivAvg[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CWDivAvg[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetKeepingCompletedEventHandler(object sender, GetKeepingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetKeepingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetKeepingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CWKeeping[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CWKeeping[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetLoanCompletedEventHandler(object sender, GetLoanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLoanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLoanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CWLoan[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CWLoan[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetLoanStmCompletedEventHandler(object sender, GetLoanStmCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLoanStmCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLoanStmCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CWLoanStm[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CWLoanStm[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetRegMemCompletedEventHandler(object sender, GetRegMemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRegMemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRegMemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CWRegister[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CWRegister[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void InsertRegCompletedEventHandler(object sender, InsertRegCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertRegCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertRegCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetRegUserCompletedEventHandler(object sender, GetRegUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRegUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRegUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CWRegister[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CWRegister[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void UpdateRegUserCompletedEventHandler(object sender, UpdateRegUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateRegUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateRegUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetShareCompletedEventHandler(object sender, GetShareCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetShareCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetShareCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CWShare[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CWShare[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetShareStmCompletedEventHandler(object sender, GetShareStmCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetShareStmCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetShareStmCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CWShareStm[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CWShareStm[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetWhocollCompletedEventHandler(object sender, GetWhocollCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWhocollCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWhocollCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CWWhocoll[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CWWhocoll[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void CheckMemberCompletedEventHandler(object sender, CheckMemberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckMemberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckMemberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetLoginCompletedEventHandler(object sender, GetLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetUserPasswordCompletedEventHandler(object sender, GetUserPasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void ChangePasswordCompletedEventHandler(object sender, ChangePasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChangePasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChangePasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591