//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 
namespace WebService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WptServiceSoap", Namespace="http://tempuri.org/")]
    public partial class WptService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMemberOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetApprvLoanOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCollwhoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDeptOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDeptStmOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDivAvgOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetKeepingOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLoanOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLoanStmOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRegMemOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertRegOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRegUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateRegUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetShareOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetShareStmOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetWhocollOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckMemberOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserPasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback ChangePasswordOperationCompleted;
        
        /// <remarks/>
        public WptService() {
            string urlSetting = System.Configuration.ConfigurationManager.AppSettings["EndpointURL"];
            if ((urlSetting != null)) {
                this.Url = urlSetting;
            }
            else {
                this.Url = "http://wswebportal/GCOOP/WsWebPortal/WptService.asmx";
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event GetMemberCompletedEventHandler GetMemberCompleted;
        
        /// <remarks/>
        public event GetApprvLoanCompletedEventHandler GetApprvLoanCompleted;
        
        /// <remarks/>
        public event GetCollwhoCompletedEventHandler GetCollwhoCompleted;
        
        /// <remarks/>
        public event GetDeptCompletedEventHandler GetDeptCompleted;
        
        /// <remarks/>
        public event GetDeptStmCompletedEventHandler GetDeptStmCompleted;
        
        /// <remarks/>
        public event GetDivAvgCompletedEventHandler GetDivAvgCompleted;
        
        /// <remarks/>
        public event GetKeepingCompletedEventHandler GetKeepingCompleted;
        
        /// <remarks/>
        public event GetLoanCompletedEventHandler GetLoanCompleted;
        
        /// <remarks/>
        public event GetLoanStmCompletedEventHandler GetLoanStmCompleted;
        
        /// <remarks/>
        public event GetRegMemCompletedEventHandler GetRegMemCompleted;
        
        /// <remarks/>
        public event InsertRegCompletedEventHandler InsertRegCompleted;
        
        /// <remarks/>
        public event GetRegUserCompletedEventHandler GetRegUserCompleted;
        
        /// <remarks/>
        public event UpdateRegUserCompletedEventHandler UpdateRegUserCompleted;
        
        /// <remarks/>
        public event GetShareCompletedEventHandler GetShareCompleted;
        
        /// <remarks/>
        public event GetShareStmCompletedEventHandler GetShareStmCompleted;
        
        /// <remarks/>
        public event GetWhocollCompletedEventHandler GetWhocollCompleted;
        
        /// <remarks/>
        public event CheckMemberCompletedEventHandler CheckMemberCompleted;
        
        /// <remarks/>
        public event GetLoginCompletedEventHandler GetLoginCompleted;
        
        /// <remarks/>
        public event GetUserPasswordCompletedEventHandler GetUserPasswordCompleted;
        
        /// <remarks/>
        public event ChangePasswordCompletedEventHandler ChangePasswordCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("HelloWorld", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndHelloWorld(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMember", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CWmember[] GetMember(string memberNo) {
            object[] results = this.Invoke("GetMember", new object[] {
                        memberNo});
            return ((CWmember[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetMember(string memberNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetMember", new object[] {
                        memberNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public CWmember[] EndGetMember(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((CWmember[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMemberAsync(string memberNo) {
            this.GetMemberAsync(memberNo, null);
        }
        
        /// <remarks/>
        public void GetMemberAsync(string memberNo, object userState) {
            if ((this.GetMemberOperationCompleted == null)) {
                this.GetMemberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMemberOperationCompleted);
            }
            this.InvokeAsync("GetMember", new object[] {
                        memberNo}, this.GetMemberOperationCompleted, userState);
        }
        
        private void OnGetMemberOperationCompleted(object arg) {
            if ((this.GetMemberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMemberCompleted(this, new GetMemberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetApprvLoan", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CWApprvLoan[] GetApprvLoan(string memberNo) {
            object[] results = this.Invoke("GetApprvLoan", new object[] {
                        memberNo});
            return ((CWApprvLoan[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetApprvLoan(string memberNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetApprvLoan", new object[] {
                        memberNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public CWApprvLoan[] EndGetApprvLoan(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((CWApprvLoan[])(results[0]));
        }
        
        /// <remarks/>
        public void GetApprvLoanAsync(string memberNo) {
            this.GetApprvLoanAsync(memberNo, null);
        }
        
        /// <remarks/>
        public void GetApprvLoanAsync(string memberNo, object userState) {
            if ((this.GetApprvLoanOperationCompleted == null)) {
                this.GetApprvLoanOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetApprvLoanOperationCompleted);
            }
            this.InvokeAsync("GetApprvLoan", new object[] {
                        memberNo}, this.GetApprvLoanOperationCompleted, userState);
        }
        
        private void OnGetApprvLoanOperationCompleted(object arg) {
            if ((this.GetApprvLoanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetApprvLoanCompleted(this, new GetApprvLoanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCollwho", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CWCollWho[] GetCollwho(string memberNO) {
            object[] results = this.Invoke("GetCollwho", new object[] {
                        memberNO});
            return ((CWCollWho[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetCollwho(string memberNO, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetCollwho", new object[] {
                        memberNO}, callback, asyncState);
        }
        
        /// <remarks/>
        public CWCollWho[] EndGetCollwho(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((CWCollWho[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCollwhoAsync(string memberNO) {
            this.GetCollwhoAsync(memberNO, null);
        }
        
        /// <remarks/>
        public void GetCollwhoAsync(string memberNO, object userState) {
            if ((this.GetCollwhoOperationCompleted == null)) {
                this.GetCollwhoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCollwhoOperationCompleted);
            }
            this.InvokeAsync("GetCollwho", new object[] {
                        memberNO}, this.GetCollwhoOperationCompleted, userState);
        }
        
        private void OnGetCollwhoOperationCompleted(object arg) {
            if ((this.GetCollwhoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCollwhoCompleted(this, new GetCollwhoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDept", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CWDept[] GetDept(string memberNo) {
            object[] results = this.Invoke("GetDept", new object[] {
                        memberNo});
            return ((CWDept[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetDept(string memberNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetDept", new object[] {
                        memberNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public CWDept[] EndGetDept(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((CWDept[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDeptAsync(string memberNo) {
            this.GetDeptAsync(memberNo, null);
        }
        
        /// <remarks/>
        public void GetDeptAsync(string memberNo, object userState) {
            if ((this.GetDeptOperationCompleted == null)) {
                this.GetDeptOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDeptOperationCompleted);
            }
            this.InvokeAsync("GetDept", new object[] {
                        memberNo}, this.GetDeptOperationCompleted, userState);
        }
        
        private void OnGetDeptOperationCompleted(object arg) {
            if ((this.GetDeptCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDeptCompleted(this, new GetDeptCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDeptStm", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CWDeptStm[] GetDeptStm(string deptAccNo) {
            object[] results = this.Invoke("GetDeptStm", new object[] {
                        deptAccNo});
            return ((CWDeptStm[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetDeptStm(string deptAccNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetDeptStm", new object[] {
                        deptAccNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public CWDeptStm[] EndGetDeptStm(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((CWDeptStm[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDeptStmAsync(string deptAccNo) {
            this.GetDeptStmAsync(deptAccNo, null);
        }
        
        /// <remarks/>
        public void GetDeptStmAsync(string deptAccNo, object userState) {
            if ((this.GetDeptStmOperationCompleted == null)) {
                this.GetDeptStmOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDeptStmOperationCompleted);
            }
            this.InvokeAsync("GetDeptStm", new object[] {
                        deptAccNo}, this.GetDeptStmOperationCompleted, userState);
        }
        
        private void OnGetDeptStmOperationCompleted(object arg) {
            if ((this.GetDeptStmCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDeptStmCompleted(this, new GetDeptStmCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDivAvg", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CWDivAvg[] GetDivAvg(string memberNo) {
            object[] results = this.Invoke("GetDivAvg", new object[] {
                        memberNo});
            return ((CWDivAvg[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetDivAvg(string memberNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetDivAvg", new object[] {
                        memberNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public CWDivAvg[] EndGetDivAvg(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((CWDivAvg[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDivAvgAsync(string memberNo) {
            this.GetDivAvgAsync(memberNo, null);
        }
        
        /// <remarks/>
        public void GetDivAvgAsync(string memberNo, object userState) {
            if ((this.GetDivAvgOperationCompleted == null)) {
                this.GetDivAvgOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDivAvgOperationCompleted);
            }
            this.InvokeAsync("GetDivAvg", new object[] {
                        memberNo}, this.GetDivAvgOperationCompleted, userState);
        }
        
        private void OnGetDivAvgOperationCompleted(object arg) {
            if ((this.GetDivAvgCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDivAvgCompleted(this, new GetDivAvgCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetKeeping", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CWKeeping[] GetKeeping(string memberNo) {
            object[] results = this.Invoke("GetKeeping", new object[] {
                        memberNo});
            return ((CWKeeping[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetKeeping(string memberNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetKeeping", new object[] {
                        memberNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public CWKeeping[] EndGetKeeping(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((CWKeeping[])(results[0]));
        }
        
        /// <remarks/>
        public void GetKeepingAsync(string memberNo) {
            this.GetKeepingAsync(memberNo, null);
        }
        
        /// <remarks/>
        public void GetKeepingAsync(string memberNo, object userState) {
            if ((this.GetKeepingOperationCompleted == null)) {
                this.GetKeepingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetKeepingOperationCompleted);
            }
            this.InvokeAsync("GetKeeping", new object[] {
                        memberNo}, this.GetKeepingOperationCompleted, userState);
        }
        
        private void OnGetKeepingOperationCompleted(object arg) {
            if ((this.GetKeepingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetKeepingCompleted(this, new GetKeepingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLoan", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CWLoan[] GetLoan(string memberNo) {
            object[] results = this.Invoke("GetLoan", new object[] {
                        memberNo});
            return ((CWLoan[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetLoan(string memberNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetLoan", new object[] {
                        memberNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public CWLoan[] EndGetLoan(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((CWLoan[])(results[0]));
        }
        
        /// <remarks/>
        public void GetLoanAsync(string memberNo) {
            this.GetLoanAsync(memberNo, null);
        }
        
        /// <remarks/>
        public void GetLoanAsync(string memberNo, object userState) {
            if ((this.GetLoanOperationCompleted == null)) {
                this.GetLoanOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLoanOperationCompleted);
            }
            this.InvokeAsync("GetLoan", new object[] {
                        memberNo}, this.GetLoanOperationCompleted, userState);
        }
        
        private void OnGetLoanOperationCompleted(object arg) {
            if ((this.GetLoanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLoanCompleted(this, new GetLoanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLoanStm", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CWLoanStm[] GetLoanStm(string lnContNo) {
            object[] results = this.Invoke("GetLoanStm", new object[] {
                        lnContNo});
            return ((CWLoanStm[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetLoanStm(string lnContNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetLoanStm", new object[] {
                        lnContNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public CWLoanStm[] EndGetLoanStm(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((CWLoanStm[])(results[0]));
        }
        
        /// <remarks/>
        public void GetLoanStmAsync(string lnContNo) {
            this.GetLoanStmAsync(lnContNo, null);
        }
        
        /// <remarks/>
        public void GetLoanStmAsync(string lnContNo, object userState) {
            if ((this.GetLoanStmOperationCompleted == null)) {
                this.GetLoanStmOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLoanStmOperationCompleted);
            }
            this.InvokeAsync("GetLoanStm", new object[] {
                        lnContNo}, this.GetLoanStmOperationCompleted, userState);
        }
        
        private void OnGetLoanStmOperationCompleted(object arg) {
            if ((this.GetLoanStmCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLoanStmCompleted(this, new GetLoanStmCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRegMem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CWRegister[] GetRegMem(string memberNO) {
            object[] results = this.Invoke("GetRegMem", new object[] {
                        memberNO});
            return ((CWRegister[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetRegMem(string memberNO, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetRegMem", new object[] {
                        memberNO}, callback, asyncState);
        }
        
        /// <remarks/>
        public CWRegister[] EndGetRegMem(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((CWRegister[])(results[0]));
        }
        
        /// <remarks/>
        public void GetRegMemAsync(string memberNO) {
            this.GetRegMemAsync(memberNO, null);
        }
        
        /// <remarks/>
        public void GetRegMemAsync(string memberNO, object userState) {
            if ((this.GetRegMemOperationCompleted == null)) {
                this.GetRegMemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRegMemOperationCompleted);
            }
            this.InvokeAsync("GetRegMem", new object[] {
                        memberNO}, this.GetRegMemOperationCompleted, userState);
        }
        
        private void OnGetRegMemOperationCompleted(object arg) {
            if ((this.GetRegMemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRegMemCompleted(this, new GetRegMemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertReg", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int InsertReg(string member, string name, string surname, string cardId, string email, string usn, string pwd) {
            object[] results = this.Invoke("InsertReg", new object[] {
                        member,
                        name,
                        surname,
                        cardId,
                        email,
                        usn,
                        pwd});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginInsertReg(string member, string name, string surname, string cardId, string email, string usn, string pwd, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("InsertReg", new object[] {
                        member,
                        name,
                        surname,
                        cardId,
                        email,
                        usn,
                        pwd}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndInsertReg(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void InsertRegAsync(string member, string name, string surname, string cardId, string email, string usn, string pwd) {
            this.InsertRegAsync(member, name, surname, cardId, email, usn, pwd, null);
        }
        
        /// <remarks/>
        public void InsertRegAsync(string member, string name, string surname, string cardId, string email, string usn, string pwd, object userState) {
            if ((this.InsertRegOperationCompleted == null)) {
                this.InsertRegOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertRegOperationCompleted);
            }
            this.InvokeAsync("InsertReg", new object[] {
                        member,
                        name,
                        surname,
                        cardId,
                        email,
                        usn,
                        pwd}, this.InsertRegOperationCompleted, userState);
        }
        
        private void OnInsertRegOperationCompleted(object arg) {
            if ((this.InsertRegCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertRegCompleted(this, new InsertRegCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRegUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CWRegister[] GetRegUser(string memberNo) {
            object[] results = this.Invoke("GetRegUser", new object[] {
                        memberNo});
            return ((CWRegister[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetRegUser(string memberNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetRegUser", new object[] {
                        memberNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public CWRegister[] EndGetRegUser(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((CWRegister[])(results[0]));
        }
        
        /// <remarks/>
        public void GetRegUserAsync(string memberNo) {
            this.GetRegUserAsync(memberNo, null);
        }
        
        /// <remarks/>
        public void GetRegUserAsync(string memberNo, object userState) {
            if ((this.GetRegUserOperationCompleted == null)) {
                this.GetRegUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRegUserOperationCompleted);
            }
            this.InvokeAsync("GetRegUser", new object[] {
                        memberNo}, this.GetRegUserOperationCompleted, userState);
        }
        
        private void OnGetRegUserOperationCompleted(object arg) {
            if ((this.GetRegUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRegUserCompleted(this, new GetRegUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateRegUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UpdateRegUser(string member, string usn, string pwd) {
            object[] results = this.Invoke("UpdateRegUser", new object[] {
                        member,
                        usn,
                        pwd});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdateRegUser(string member, string usn, string pwd, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UpdateRegUser", new object[] {
                        member,
                        usn,
                        pwd}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndUpdateRegUser(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateRegUserAsync(string member, string usn, string pwd) {
            this.UpdateRegUserAsync(member, usn, pwd, null);
        }
        
        /// <remarks/>
        public void UpdateRegUserAsync(string member, string usn, string pwd, object userState) {
            if ((this.UpdateRegUserOperationCompleted == null)) {
                this.UpdateRegUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateRegUserOperationCompleted);
            }
            this.InvokeAsync("UpdateRegUser", new object[] {
                        member,
                        usn,
                        pwd}, this.UpdateRegUserOperationCompleted, userState);
        }
        
        private void OnUpdateRegUserOperationCompleted(object arg) {
            if ((this.UpdateRegUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateRegUserCompleted(this, new UpdateRegUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetShare", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CWShare[] GetShare(string memberNo) {
            object[] results = this.Invoke("GetShare", new object[] {
                        memberNo});
            return ((CWShare[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetShare(string memberNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetShare", new object[] {
                        memberNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public CWShare[] EndGetShare(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((CWShare[])(results[0]));
        }
        
        /// <remarks/>
        public void GetShareAsync(string memberNo) {
            this.GetShareAsync(memberNo, null);
        }
        
        /// <remarks/>
        public void GetShareAsync(string memberNo, object userState) {
            if ((this.GetShareOperationCompleted == null)) {
                this.GetShareOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetShareOperationCompleted);
            }
            this.InvokeAsync("GetShare", new object[] {
                        memberNo}, this.GetShareOperationCompleted, userState);
        }
        
        private void OnGetShareOperationCompleted(object arg) {
            if ((this.GetShareCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetShareCompleted(this, new GetShareCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetShareStm", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CWShareStm[] GetShareStm(string memberNo) {
            object[] results = this.Invoke("GetShareStm", new object[] {
                        memberNo});
            return ((CWShareStm[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetShareStm(string memberNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetShareStm", new object[] {
                        memberNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public CWShareStm[] EndGetShareStm(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((CWShareStm[])(results[0]));
        }
        
        /// <remarks/>
        public void GetShareStmAsync(string memberNo) {
            this.GetShareStmAsync(memberNo, null);
        }
        
        /// <remarks/>
        public void GetShareStmAsync(string memberNo, object userState) {
            if ((this.GetShareStmOperationCompleted == null)) {
                this.GetShareStmOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetShareStmOperationCompleted);
            }
            this.InvokeAsync("GetShareStm", new object[] {
                        memberNo}, this.GetShareStmOperationCompleted, userState);
        }
        
        private void OnGetShareStmOperationCompleted(object arg) {
            if ((this.GetShareStmCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetShareStmCompleted(this, new GetShareStmCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetWhocoll", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CWWhocoll[] GetWhocoll(string memberNo) {
            object[] results = this.Invoke("GetWhocoll", new object[] {
                        memberNo});
            return ((CWWhocoll[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetWhocoll(string memberNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetWhocoll", new object[] {
                        memberNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public CWWhocoll[] EndGetWhocoll(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((CWWhocoll[])(results[0]));
        }
        
        /// <remarks/>
        public void GetWhocollAsync(string memberNo) {
            this.GetWhocollAsync(memberNo, null);
        }
        
        /// <remarks/>
        public void GetWhocollAsync(string memberNo, object userState) {
            if ((this.GetWhocollOperationCompleted == null)) {
                this.GetWhocollOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWhocollOperationCompleted);
            }
            this.InvokeAsync("GetWhocoll", new object[] {
                        memberNo}, this.GetWhocollOperationCompleted, userState);
        }
        
        private void OnGetWhocollOperationCompleted(object arg) {
            if ((this.GetWhocollCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWhocollCompleted(this, new GetWhocollCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckMember", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CheckMember(string memberNo, string cardPerson) {
            object[] results = this.Invoke("CheckMember", new object[] {
                        memberNo,
                        cardPerson});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCheckMember(string memberNo, string cardPerson, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CheckMember", new object[] {
                        memberNo,
                        cardPerson}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndCheckMember(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CheckMemberAsync(string memberNo, string cardPerson) {
            this.CheckMemberAsync(memberNo, cardPerson, null);
        }
        
        /// <remarks/>
        public void CheckMemberAsync(string memberNo, string cardPerson, object userState) {
            if ((this.CheckMemberOperationCompleted == null)) {
                this.CheckMemberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckMemberOperationCompleted);
            }
            this.InvokeAsync("CheckMember", new object[] {
                        memberNo,
                        cardPerson}, this.CheckMemberOperationCompleted, userState);
        }
        
        private void OnCheckMemberOperationCompleted(object arg) {
            if ((this.CheckMemberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckMemberCompleted(this, new CheckMemberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLogin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetLogin(string[] arr) {
            object[] results = this.Invoke("GetLogin", new object[] {
                        arr});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetLogin(string[] arr, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetLogin", new object[] {
                        arr}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetLogin(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetLoginAsync(string[] arr) {
            this.GetLoginAsync(arr, null);
        }
        
        /// <remarks/>
        public void GetLoginAsync(string[] arr, object userState) {
            if ((this.GetLoginOperationCompleted == null)) {
                this.GetLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLoginOperationCompleted);
            }
            this.InvokeAsync("GetLogin", new object[] {
                        arr}, this.GetLoginOperationCompleted, userState);
        }
        
        private void OnGetLoginOperationCompleted(object arg) {
            if ((this.GetLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLoginCompleted(this, new GetLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserPassword", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetUserPassword(string memberNo, string emailAddr) {
            object[] results = this.Invoke("GetUserPassword", new object[] {
                        memberNo,
                        emailAddr});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetUserPassword(string memberNo, string emailAddr, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetUserPassword", new object[] {
                        memberNo,
                        emailAddr}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetUserPassword(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserPasswordAsync(string memberNo, string emailAddr) {
            this.GetUserPasswordAsync(memberNo, emailAddr, null);
        }
        
        /// <remarks/>
        public void GetUserPasswordAsync(string memberNo, string emailAddr, object userState) {
            if ((this.GetUserPasswordOperationCompleted == null)) {
                this.GetUserPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserPasswordOperationCompleted);
            }
            this.InvokeAsync("GetUserPassword", new object[] {
                        memberNo,
                        emailAddr}, this.GetUserPasswordOperationCompleted, userState);
        }
        
        private void OnGetUserPasswordOperationCompleted(object arg) {
            if ((this.GetUserPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserPasswordCompleted(this, new GetUserPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ChangePassword", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ChangePassword(string memberNO, string user, string oldpwd, string newpwd, string confpwd) {
            object[] results = this.Invoke("ChangePassword", new object[] {
                        memberNO,
                        user,
                        oldpwd,
                        newpwd,
                        confpwd});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginChangePassword(string memberNO, string user, string oldpwd, string newpwd, string confpwd, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ChangePassword", new object[] {
                        memberNO,
                        user,
                        oldpwd,
                        newpwd,
                        confpwd}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndChangePassword(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ChangePasswordAsync(string memberNO, string user, string oldpwd, string newpwd, string confpwd) {
            this.ChangePasswordAsync(memberNO, user, oldpwd, newpwd, confpwd, null);
        }
        
        /// <remarks/>
        public void ChangePasswordAsync(string memberNO, string user, string oldpwd, string newpwd, string confpwd, object userState) {
            if ((this.ChangePasswordOperationCompleted == null)) {
                this.ChangePasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChangePasswordOperationCompleted);
            }
            this.InvokeAsync("ChangePassword", new object[] {
                        memberNO,
                        user,
                        oldpwd,
                        newpwd,
                        confpwd}, this.ChangePasswordOperationCompleted, userState);
        }
        
        private void OnChangePasswordOperationCompleted(object arg) {
            if ((this.ChangePasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChangePasswordCompleted(this, new ChangePasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CWmember {
        
        /// <remarks/>
        public string MembName;
        
        /// <remarks/>
        public string MembSurname;
        
        /// <remarks/>
        public string MemberNo;
        
        /// <remarks/>
        public System.DateTime MemberDate;
        
        /// <remarks/>
        public System.DateTime BirthDate;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CWWhocoll {
        
        /// <remarks/>
        public string LnContNo;
        
        /// <remarks/>
        public string Description;
        
        /// <remarks/>
        public double PrncBal;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CWShareStm {
        
        /// <remarks/>
        public string ShareTypeCode;
        
        /// <remarks/>
        public string ShaItemTypeCode;
        
        /// <remarks/>
        public string ShaItemTypeDesc;
        
        /// <remarks/>
        public double ShareAmount;
        
        /// <remarks/>
        public double ShareValue;
        
        /// <remarks/>
        public int SeqNo;
        
        /// <remarks/>
        public System.DateTime OprDate;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CWShare {
        
        /// <remarks/>
        public double ShareStkAmt;
        
        /// <remarks/>
        public double ShareBeginAmt;
        
        /// <remarks/>
        public double PeriodShareAmt;
        
        /// <remarks/>
        public double ShareValue;
        
        /// <remarks/>
        public double PeriodBaseAmat;
        
        /// <remarks/>
        public int LastPeriod;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CWRegister {
        
        /// <remarks/>
        public string MemberNo;
        
        /// <remarks/>
        public string MembName;
        
        /// <remarks/>
        public string MembSurname;
        
        /// <remarks/>
        public string CardPerson;
        
        /// <remarks/>
        public string UserName;
        
        /// <remarks/>
        public string Password;
        
        /// <remarks/>
        public string EmailAddress;
        
        /// <remarks/>
        public string ConfPass;
        
        /// <remarks/>
        public string OldPass;
        
        /// <remarks/>
        public string NewPass;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CWLoanStm {
        
        /// <remarks/>
        public string LncontNo;
        
        /// <remarks/>
        public string BranchId;
        
        /// <remarks/>
        public string LnTypeCode;
        
        /// <remarks/>
        public string RefDocNo;
        
        /// <remarks/>
        public string MoneyTypeCode;
        
        /// <remarks/>
        public string EntryId;
        
        /// <remarks/>
        public int SeqNO;
        
        /// <remarks/>
        public int Period;
        
        /// <remarks/>
        public int ItemStatus;
        
        /// <remarks/>
        public System.DateTime SlipDate;
        
        /// <remarks/>
        public System.DateTime OprDate;
        
        /// <remarks/>
        public System.DateTime CalintForm;
        
        /// <remarks/>
        public System.DateTime CalintTo;
        
        /// <remarks/>
        public System.DateTime EntryDate;
        
        /// <remarks/>
        public double PrncPayment;
        
        /// <remarks/>
        public double InterestPayment;
        
        /// <remarks/>
        public double PrncBal;
        
        /// <remarks/>
        public double BfintarrearAmt;
        
        /// <remarks/>
        public double InterestPeriod;
        
        /// <remarks/>
        public double InterestArrear;
        
        /// <remarks/>
        public double InterestReturn;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CWLoan {
        
        /// <remarks/>
        public string LnContNo;
        
        /// <remarks/>
        public string LnTypeCode;
        
        /// <remarks/>
        public double PrncBal;
        
        /// <remarks/>
        public double PeriodPayment;
        
        /// <remarks/>
        public double LnReqAmt;
        
        /// <remarks/>
        public System.DateTime StartContDate;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CWKeeping {
        
        /// <remarks/>
        public int Seqno;
        
        /// <remarks/>
        public string KeepTypeDesc;
        
        /// <remarks/>
        public string RecvPeriod;
        
        /// <remarks/>
        public double ItemPayment;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CWDivAvg {
        
        /// <remarks/>
        public int DivAvgYear;
        
        /// <remarks/>
        public double DivAmt;
        
        /// <remarks/>
        public double AvgAmt;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CWDeptStm {
        
        /// <remarks/>
        public double DeptItemAmt;
        
        /// <remarks/>
        public double PrncBal;
        
        /// <remarks/>
        public int SeqNo;
        
        /// <remarks/>
        public string DeptTypeCode;
        
        /// <remarks/>
        public string DeptAccNo;
        
        /// <remarks/>
        public System.DateTime OprDate;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CWDept {
        
        /// <remarks/>
        public string DeptAccNo;
        
        /// <remarks/>
        public string DeptAccName;
        
        /// <remarks/>
        public string DeptTypeDesc;
        
        /// <remarks/>
        public double Prncbal;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CWCollWho {
        
        /// <remarks/>
        public string LnContNo;
        
        /// <remarks/>
        public string Description;
        
        /// <remarks/>
        public string MembName;
        
        /// <remarks/>
        public string MembSurname;
        
        /// <remarks/>
        public double _PrincBal;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CWApprvLoan {
        
        /// <remarks/>
        public string LnReqDocNo;
        
        /// <remarks/>
        public string LnTypeCode;
        
        /// <remarks/>
        public string LnTypeDesc;
        
        /// <remarks/>
        public string LnContNO;
        
        /// <remarks/>
        public double LnReqAmt;
        
        /// <remarks/>
        public double LnAppvAmt;
        
        /// <remarks/>
        public int LnReqStatus;
        
        /// <remarks/>
        public System.DateTime AppvDate;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GetMemberCompletedEventHandler(object sender, GetMemberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMemberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMemberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CWmember[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CWmember[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GetApprvLoanCompletedEventHandler(object sender, GetApprvLoanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetApprvLoanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetApprvLoanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CWApprvLoan[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CWApprvLoan[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GetCollwhoCompletedEventHandler(object sender, GetCollwhoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCollwhoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCollwhoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CWCollWho[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CWCollWho[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GetDeptCompletedEventHandler(object sender, GetDeptCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDeptCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDeptCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CWDept[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CWDept[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GetDeptStmCompletedEventHandler(object sender, GetDeptStmCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDeptStmCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDeptStmCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CWDeptStm[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CWDeptStm[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GetDivAvgCompletedEventHandler(object sender, GetDivAvgCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDivAvgCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDivAvgCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CWDivAvg[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CWDivAvg[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GetKeepingCompletedEventHandler(object sender, GetKeepingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetKeepingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetKeepingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CWKeeping[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CWKeeping[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GetLoanCompletedEventHandler(object sender, GetLoanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLoanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLoanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CWLoan[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CWLoan[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GetLoanStmCompletedEventHandler(object sender, GetLoanStmCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLoanStmCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLoanStmCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CWLoanStm[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CWLoanStm[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GetRegMemCompletedEventHandler(object sender, GetRegMemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRegMemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRegMemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CWRegister[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CWRegister[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void InsertRegCompletedEventHandler(object sender, InsertRegCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertRegCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertRegCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GetRegUserCompletedEventHandler(object sender, GetRegUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRegUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRegUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CWRegister[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CWRegister[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void UpdateRegUserCompletedEventHandler(object sender, UpdateRegUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateRegUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateRegUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GetShareCompletedEventHandler(object sender, GetShareCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetShareCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetShareCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CWShare[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CWShare[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GetShareStmCompletedEventHandler(object sender, GetShareStmCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetShareStmCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetShareStmCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CWShareStm[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CWShareStm[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GetWhocollCompletedEventHandler(object sender, GetWhocollCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWhocollCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWhocollCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CWWhocoll[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CWWhocoll[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void CheckMemberCompletedEventHandler(object sender, CheckMemberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckMemberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckMemberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GetLoginCompletedEventHandler(object sender, GetLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GetUserPasswordCompletedEventHandler(object sender, GetUserPasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void ChangePasswordCompletedEventHandler(object sender, ChangePasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChangePasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChangePasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}
